version: '3'
services:
    redis:
        image: "redis"
        ports:
        - "6379:6379"
        expose:
        - 6379
    mongo:
        image: "mongo:latest"
        ports:
        - "27017:27017"
        expose:
        - 27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
